version: '3.9'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Data Source=movies.db
      - ASPNETCORE_HTTP_PORTS=8080
    command: /bin/bash -c "/app/entrypoint.sh"
