version: '3.9'

services:
  backend:
    build:
      context: ./  # Make sure this includes both backend and backend.Tests
      dockerfile: ./backend/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Data Source=movies.db
      - ASPNETCORE_HTTP_PORTS=8080
    command: /bin/bash -c "/app/backend/entrypoint.sh"
