version: "3.9"

services:
  backend:
    build:
      context: ./ # Make sure this includes both backend and backend.Tests
      dockerfile: ./backend/Dockerfile
    ports:
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Data Source=movies.db
      - ASPNETCORE_HTTP_PORTS=8081
    command: /bin/bash -c "/app/backend/entrypoint.sh"
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:8080"
    depends_on:
      - backend
